/**
 * Author model
 * Represents authors synced from User model
 *
 * Fields:
 * - _id: author ID (String) - auto-generated by MongoDB
 * - name: author's name (String)
 */

const mongoose = require("mongoose");

const authorSchema = new mongoose.Schema(
  {
    // _id field is automatically created by MongoDB
    name: { type: String, required: true, unique: true }, // author's name
  },
  {
    versionKey: false, // do not create __v field
  }
);

const Author = mongoose.model("Author", authorSchema);

module.exports = Author;
